# Configuração para Deploy no Render
# Sistema de Gerenciamento de Restaurante

services:
  - type: web
    name: restaurante-backend
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: restaurante-postgres
          property: connectionString
      - key: PORT
        value: 3000

databases:
  - name: restaurante-postgres
    plan: free
    databaseName: restaurante_db
    user: restaurante_user

